apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-serv
  name: nginx-serv
spec:
  ports:
    - name: $-$
      port: $
      protocol: $$
      targetPort: $
  selector:
    app: nginx-serv
  type: ClusterIP
status:
  loadBalancer: {}
