[automount]
enable=true
mountFsTab=true
root=/mnt/
options="uid=1000,gid=1000"

[boot]
# command =
protectBinfmt=true
systemd=true 

[gpu]
enabled=false

[interop]
enabled=true 
appendWindowsPath=true 

[network]
generateHosts=true
generateResolvConf=true
# hostname = 

[time]
useWindowsTimezone=true

[user]
# default = 